### ISSUE TITLE
Plugin does not seem to work when you don't have Gradle installed

### ISSUE THREAD

**Issue by remy-tiitre** [jfrog/jfrog-idea-plugin#141]
**Describe the bug**
All our projects are using gradle wrapper, so Gradle itself is not installed to my system and its not in my path. Does it mean that the plugin does not work with Gradle wrapper? Connecting to Xray works and CI tab works as well. Its the local tab thats failing.

**Versions**
- IntelliJ IDEA 2021.1.3 Ultimate Edition
- JFrog IDEA plugin version: 1.9.1
- Operating system: MacOS 10.15.7
- Xray version: 3.27.2

**Additional context**
```
20:44	JFrog Xray scan failed: [ERROR] Could not scan Gradle project dependencies, because Gradle CLI is not in the PATH.

20:44	JFrog Xray scan failed
			[ERROR] 
			java.lang.NullPointerException
			at com.jfrog.ide.common.scan.ScanManagerBase.extractComponents(ScanManagerBase.java:132)
			at com.jfrog.ide.common.scan.ScanManagerBase.scanAndCacheArtifacts(ScanManagerBase.java:150)
			at com.jfrog.ide.idea.scan.ScanManager.scanAndUpdate(ScanManager.java:108)
			at com.jfrog.ide.idea.scan.ScanManager$1.run(ScanManager.java:145)
			at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
			at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
			at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
			at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
			at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
			at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgr... (show balloon)

```

**Comment by remy-tiitre** [comment]
I tracked down the issue, its not that Gradle wrapper is missing but when you have a space in folder name then this https://github.com/jfrog/ide-plugins-common/blob/38622858a6d564268ac82a2a7b7aa70c15fd5403/src/main/java/com/jfrog/ide/common/gradle/GradleDriver.java#L38 fails to find the wrapper. All my projects are under "Local Documents" folder under my profile.
