### ISSUE TITLE
Error 401 when scan maven project in IntelliJ IDEA

### ISSUE THREAD

**Issue by xingao0803** [jfrog/jfrog-idea-plugin#162]
IntelliJ IDEA:  2021.2.2
JFrog Plugin: 1.10.1
Artifactory: 7.27.3
Xray: 3.31.1

Test connection successfully.

When scan maven project, get error:

status code: 401, reason phrase: Received 401 HTTP/1.1 401 Unauthorized response from Xray
				[ERROR] Xray Scan failed: HttpResponseException: status code: 401, reason phrase: Received 401 HTTP/1.1 401 Unauthorized response from Xray
				org.apache.http.client.HttpResponseException: status code: 401, reason phrase: Received 401 HTTP/1.1 401 Unauthorized response from Xray
				at com.jfrog.xray.client.impl.XrayClient.setHeadersAndExecute(XrayClient.java:130)
				at com.jfrog.xray.client.impl.XrayClient.post(XrayClient.java:103)
				at com.jfrog.xray.client.impl.services.graph.GraphImpl.post(GraphImpl.java:62)
				at com.jfrog.xray.client.impl.services.graph.GraphImpl.graph(GraphImpl.java:56)
				at com.jfrog.ide.common.scan.GraphScanLogic.scanComponentsWithoutContext(GraphScanLogic.java:174)
				at com.jfrog.ide.common.scan.GraphScanLogic.scanComponents(GraphScanLogic.java:146)
				at com.jfrog.ide.common.scan.GraphScanLogic.scanAndCacheArtifacts(GraphScanLogic.java:72)
				at com.jfrog.ide.common.scan.ScanManagerBase.scanAndCacheArtifacts(ScanManagerBase.java:116)
				at com.jfrog.ide.idea.scan.ScanManager.s... (show balloon)

**Comment by xingao0803** [comment]
@yahavi 
Hello, Thanks for the response.

I tried your suggestions:
1. Upgraded the plugin to 1.10.2, and the 401 error still exists.
2. Set Intellij's PasswordSafe to store passwords to native KayChain, and fill in MacOS's password when asks.  The 401 error still exists.  (Any ways to confirm the JFrog's passwords really stored in KeyChain and Intellij can read them?)
3. There is no proxy between Intellij and Xray/Artifactory on port 8082. There is a nginx, but it only forward from port 80 to port 8082.
    I also run the curl command in the root folder of the project, but nothing returned.  Is there any problems? How can I further   investigate it?

4. BTW, are there any settings needed in Xray?  The Xray 3.31.2 was upgraded from 3.27, and in 3.27 the plugin worked well.

Thanks.

**Comment by talarian1** [comment]
Hi @xingao0803 

Regrading the curl command output, an expected output is: {"scan_id":"..."} or in case of an error : {"error":"..."}.
Which kind of response are you getting?

**Comment by yahavi** [comment]
@xingao0803 did you manage to figure out the root cause of this issue?

**Comment by xingao0803** [comment]
@yahavi No.  But it must be configuration errors in my Xray V3.31, because my Xray V3.32 works well.  It should not be the plugin errors, so I closed the issue.
