### ISSUE TITLE
Dealing with circular dependencies in Python

### ISSUE THREAD

**Issue by flupzor** [jfrog/jfrog-idea-plugin#318]
**Describe the bug**
I can't share the packages, since they are internal. But there are 2 packages both have each other as requirements in setup.py

So:
Package A setup.py:
...
install_requires = ['B', ]
...

Package B setup.py
...
install_requires = ['A', ]
...

When I try to do a local Jfrog scan on this project, the scan crashes with the following exception. However, if I remove package A it successfully scans, and I get scan results.

I found the following code which does a recursive scan without checking for circular dependencies. Which would explain this bug.

https://github.com/jfrog/jfrog-idea-plugin/blob/2.1.1/src/main/java/com/jfrog/ide/idea/scan/PypiScanner.java#L144

```
java.lang.StackOverflowError
	at com.jfrog.ide.common.utils.Utils.createComponentId(Utils.java:47)
	at com.jfrog.ide.idea.scan.PypiScanner.initDependencyNode(PypiScanner.java:158)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:135)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
	at com.jfrog.ide.idea.scan.PypiScanner.populateDependencyTree(PypiScanner.java:144)
... etcetera
```

**To Reproduce**

As mentioned above, it requires two package which depend on each-other to reproduce the issue. Sadly I don't have any public example of this.

**Expected behavior**

Expected behavior is a successful scan.

**Screenshots**
N/A

**Versions**
- JFrog IDEA plugin version: 2.1.1
- Operating system: macos 12.6.3
- Xray version: Enterprise Plus 7.41.7

**Comment by talarian1** [comment]
Hi @flupzor thanks for reporting this issue.
JFrog Idea Plugin 2.2.0 is released and includes a fix for this issue. 
We would appreciate any feedback on that.
