### ISSUE TITLE
Xray Scan failed: NullPointerException: Cannot invoke "java.util.List.iterator()"

### ISSUE THREAD

**Issue by Jan-Pleva** [jfrog/jfrog-idea-plugin#353]
**Describe the bug**
When we run Xray analysis, the plugin show error with no results.

**To Reproduce**
Not sure.

**Expected behavior**
Show the results of scan

**Screenshots**
no

**Versions**
- JFrog IDEA plugin version: latest 2.2.5
- Operating system: Windows 10
- Xray version: 3.62.4
![image](https://github.com/jfrog/jfrog-idea-plugin/assets/71633160/32e05a7a-05f4-4da5-9e97-dd427321a2aa)

**Additional context**
Xray Scan failed: NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "java.util.Map.get(Object)" is null

2023-05-29 13:32:18,118 [ 304802]   WARN - #com.jfrog.ide.idea.log.Logger - Xray Scan failed: NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "java.util.Map.get(Object)" is null
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "java.util.Map.get(Object)" is null
    at com.jfrog.ide.idea.scan.ScannerBase.createImpactPaths(ScannerBase.java:208)
    at com.jfrog.ide.idea.scan.ScannerBase.scanAndUpdate(ScannerBase.java:163)
    at com.jfrog.ide.idea.scan.ScannerBase$1.run(ScannerBase.java:255)
    at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:423)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:474)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by asafgabai** [comment]
Hi @Jan-Pleva, thank you for bringing this to our attention. It would be helpful if you could provide some information about the type of project you are attempting to scan (Maven/Gradle/npm/Yarn/Go/Python).

**Comment by asafgabai** [comment]
@Jan-Pleva The code has been refactored in the latest plugin release (2.2.6). We recommend upgrading to this version and kindly ask for your feedback if the issue persists.

**Comment by KamilVolf** [comment]
Hi all. I found same issue od version 
JFrog IDEA plugin version: latest 2.7.1
Operating system: Windows 11
Xray version: 3.96.1
Intellij IDEA version: 2024.2.3

Maven/Gradle project - same issue

Xray scan failed: NullPointerException: Cannot invoke "java.util.Set.contains(Object)" because the return value of "java.util.Map.get(Object)" is null
