### ISSUE TITLE
JFROG Plugin cannot scan the dependency tree

### ISSUE THREAD

**Issue by buscha64** [jfrog/jfrog-idea-plugin#382]
I got following error:

[ERROR] Xray scan failed: IOException: FAILURE: Build failed with an exception. * What went wrong: java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file C:\Users\FWolf\.gradle\caches\jars-9\ba996557e7d64c47da7a273bf722472f\jackson-core-2.15.2.jar. > org.gradle.api.GradleException: Failed to create Jar file C:\Users\FWolf\.gradle\caches\jars-9\ba996557e7d64c47da7a273bf722472f\jackson-core-2.15.2.jar. * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org/ BUILD FAILED in 7s java.io.IOException: Couldn't build Gradle dependency tree in workspace 'D:\projects\services\KidicapServices-delivery': IOException: FAILURE: Build failed with an exception. * What went wrong: java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file C:\Users\FWolf\.gradle\caches\jars-9\ba996557e7d64c47da7a273bf722472f\jackson-core-2.15.2.jar. > org.gradle.api.GradleException: Failed to create Jar file C:\Users\FWolf\.gradle\caches\jars-9\ba996557e7d64c47da7a273bf722472f\jackson-core-2.15.2.jar. * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org/ BUILD FAILED in 7s at com.jfrog.ide.common.gradle.GradleDriver.generateDependenciesGraphAsJson(GradleDriver.java:93) at com.jfrog.ide.common.gradle.GradleTreeBuilder.buildTree(GradleTreeBuilder.java:47) at com.jfrog.ide.idea.scan.GradleScanner.buildTree(GradleScanner.java:100) at com.jfrog.ide.idea.scan.ScannerBase.scanAndUpdate(ScannerBase.java:138) at com.jfrog.ide.idea.scan.ScannerBase$1.run(ScannerBase.java:287) at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429) at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480) at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679) at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173) at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699) at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699) at java.base/java.lang.Thread.run(Thread.java:833) Caused by: java.io.IOException: FAILURE: Build failed with an exception. * What went wrong: java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file C:\Users\FWolf\.gradle\caches\jars-9\ba996557e7d64c47da7a273bf722472f\jackson-core-2.15.2.jar. > org.gradle.api.GradleException: Failed to create Jar file C:\Users\FWolf\.gradle\caches\jars-9\ba996557e7d64c47da7a273bf722472f\jackson-core-2.15.2.jar. * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org/ BUILD FAILED in 7s at com.jfrog.ide.common.gradle.GradleDriver.runCommand(GradleDriver.java:107) at com.jfrog.ide.common.gradle.GradleDriver.generateDependenciesGraphAsJson(GradleDriver.java:81) ... 24 more

**Comment by buscha64** [comment]
I opened an incident by JFROG under: #260404
