### ISSUE TITLE
Scan failed when scanning some projects, getting partial results

### ISSUE THREAD

**Issue by erick-duran** [jfrog/jfrog-idea-plugin#83]
**Describe the bug**
We are receiving the following error when triggering manual scans using IntelliJ.
```
[ERROR] Scan failed org.apache.http.NoHttpResponseException: artifactory-url:80 failed to respond at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141) at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) at org.jfrog.client.http.CloseableHttpClientDecorator.doExecute(CloseableHttpClientDecorator.java:107) at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) at com.jfrog.xray.client.impl.XrayImpl.setHeadersAndExecute(XrayImpl.java:107) at com.jfrog.xray.client.impl.XrayImpl.post(XrayImpl.java:97) at com.jfrog.xray.client.impl.services.summary.SummaryImpl.post(SummaryImpl.java:54) at com.jfrog.xray.client.impl.services.summary.SummaryImpl.component(SummaryImpl.java:45) at com.jfrog.ide.common.scan.ScanManagerBase.scanComponents(ScanManagerBase.java:216) atcom.jfrog.ide.common.scan.ScanManagerBase.scanAndCacheArtifacts(ScanManagerBase.java:176) at com.jfrog.ide.idea.scan.ScanManager.access$100(ScanManager.java:52) at com.jfrog.ide.idea.scan.ScanManager$2.onSuccess(ScanManager.java:159) at com.jfrog.ide.idea.scan.NpmScanManager.refreshDependencies(NpmScanManager.java:42) at com.jfrog.ide.idea.scan.ScanManager.scanAndUpdate(ScanManager.java:104) at com.jfrog.ide.idea.scan.ScanManager.access$000(ScanManager.java:52) at com.jfrog.ide.idea.scan.ScanManager$1.run(ScanManager.java:123) at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932) at
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:434) at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153) at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834)
```
Some components get results, but others get partial vulnerabilities and licenses. Others don't even get licenses (they appear all green).

**To Reproduce**
1. Start IntelliJ
2. Configure credentials (user/key)
3. Trigger scan from plugin window (refresh scan button)

**Expected behavior**
Retrieve complete scan results with no errors

**Versions**
- JFrog IDEA plugin version: 1.6.1 (happening since 1.5)
- Operating system: MacOS
- Xray version: 3.5.2 (happening since 3.x)

**Additional context**
I have monitored the scans at the same time while triggering the scan for our Xray nodes. The components trigger scans, I get output like this for all of the components:
```
2020-06-22T18:18:55.685Z [jfxr ] [INFO ] [                ] [HttpHandlerExt:94             ] [main                ] Scan Artifact component, componentId : gav://com.fasterxml.jackson.module:jackson-module-parameter-names:2.9.6
```
But the plugin returns the error while Xray seems to be still triggering scans. Seems to me that something is ending the connection before IntelliJ is able to retrieve the scan results.

Enterprise support ticket #132427

**Comment by yahavi** [comment]
@erick-duran,
Thanks for reporting this issue! Do you still have it?
